apiVersion: apps/v1
kind: deployment
metadata:
  name: nginx0-deployment
  labels:
    app: nginx0-deployment
spec:
   selector:
     matchLabels:
       app: nginx0
       version: v1
  replicas: 2
  selector:
    matchLabels:
      app: nginx0
  template:
    metadata:
      labels:
        app: nginx0
    spec:
         imagePullSecrets:
         - name: regcred
         containers:
         - name: nginx
           image: azuretoolsacr.azurecr.io/nginx:v1
           imagePullPolicy: Always
         ports:
         - containerPort: 80
 
