apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
<<<<<<< HEAD
      - name: frontend
        image: azuretoolsacr.azurecr.io/frontend:v6
=======
      - name: nginx
<<<<<<< HEAD
        image: azuretoolsacr.azurecr.io/frontend:latest
>>>>>>> b8d29e373f0f086556b2ca620731b01d132e46a4
=======
        image: azuretoolsacr.azurecr.io/frontend:v6
>>>>>>> 149586522ca75e3c9924140f9fd1b30d916d010e
        imagePullPolicy: Always
        ports:
        - containerPort: 80