apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  labels:
    app: frontend
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        env: dev
    spec:
      containers:
      - name: flask
        image: cloudlifeacr.azurecr.io/frontend
        ports:
        - name:  http
          containerPort: 8080
          protocol: TCP
