apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      run: frontend-deployment
  replicas: 2
  template:
    metadata:
      labels:
        run: frontend-deployment
    spec:
      containers:
      - name: frontend-deployment
        image:  azuretoolsacr.azurecr.io/frontend:v1
        ports:
        - containerPort: 80


