apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  namespace: default
spec:
  containers:
    - name: main-app-container
      image: azuretoolsacr.azurecr.io/nginx:v1
      imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: regcred
