name: Deploy to AKS Cluster
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: Azure/docker-login@v1
      with:
        login-server: azuretoolsacr.azurecr.io
        username: ${{ secrets.ACR_USER }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - run: |
        docker build . -t azuretoolsacr.azurecr.io/frontend:${{ github.sha }}
        docker push azuretoolsacr.azurecr.io/frontend:${{ github.sha }}
        docker build . -t azuretoolsacr.azurecr.io/backend:${{ github.sha }}
        docker push azuretoolsacr.azurecr.io/backend:${{ github.sha }}
        
      
#     # Set the target AKS cluster.
#     - uses: Azure/aks-set-context@v1
#       with:
#         creds: '${{ secrets.AZURE_CREDENTIALS }}'
#         cluster-name: toolsakscluster
#         resource-group: azure-automation-rg
      
    - name: 📃 Set AKS context
      uses: azure/K8S-set-context@v1
      with:
       method: kubeconfig
       kubeconfig: ${{ secrets.KUBE_CONFIG }}
       
        
    - uses: Azure/k8s-create-secret@v1
      with:
        container-registry-url: azuretoolsacr.azurecr.io
        container-registry-username: ${{ secrets.ACR_USER }}
        container-registry-password: ${{ secrets.ACR_PASSWORD }}
        secret-name: azuretoolscred

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/deployment.yaml
          manifests/service.yaml
        images: |
          azuretoolsacr.azurecr.io/frontend:${{ github.sha }}
        imagepullsecrets: |
          azuretoolscred
